name: Run DBT project
run-name: Run DBT project
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  DBT_RUN:
    name: Deploy models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' 
          
      - name: install DBT Databricks adaptor
        run: pip install -q dbt-databricks

      - name: generate profiles.yml
        env: 
          profiles: ${{secrets.PROFILES}}
        run: |
          touch ./profiles.yml
          echo "$profiles" >> ./profiles.yml

      - name: dbt debug
        run: dbt debug

      - name: dbt run
        run: dbt run
