name: Run DBT project
run-name: Run DBT project
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  DBT_RUN:
    name: Deploy models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: generate profiles.yml
        env: 
          profiles: ${{secrets.PROFILES}}
        run: |
          touch ./profiles.yml
          echo "$profiles" >> ./profiles.yml

      - name: dbt debug
        run: dbt debug

      - name: dbt run
        run: dbt run
